name: Publish Package to TestPyPI

on:
  push:
    branches:
      - pip_package_ci

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Set up FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v2
    
    - name: Install Additional requirements
      run: |
        sudo apt-get -y install portaudio19-dev wget
      shell: bash

    - name: Install Client Requirements
      run: pip install -r requirements/client.txt

    - name: Install Server Requirements
      run: pip install -r requirements/server.txt

    - name: Install Wheel for build 
      run: pip install wheel twine
    
    - name: Build and Publish Package to TestPyPI
      run: |
        python setup.py sdist bdist_wheel
        versioned_wheel=$(echo "dist/*cp${{ matrix.python-version }}*")
        twine upload --repository-url https://test.pypi.org/legacy/ $versioned_wheel
      env:
        TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
